import assert from 'node:assert/strict';
import { NullEngine, Scene, MeshBuilder, Vector3 } from '@babylonjs/core';
import { createGrenades } from '../game/createGrenade.ts';
import { applyWeaponDamage } from '../game/weaponDefinitions.ts';
const engine = new NullEngine(); const scene = new Scene(engine);
let explosions = 0, position;
const grenades = createGrenades(scene, point => { explosions++; position = point; });
grenades.throw(new Vector3(0, 20, 0), new Vector3(0, 0, 1));
grenades.update(1); assert.equal(explosions, 0);
grenades.update(.99); assert.equal(explosions, 0);
grenades.update(.01 + 1e-9); assert.equal(explosions, 1, 'fuse includes flight');
grenades.update(3); assert.equal(explosions, 1, 'one detonation');
assert.ok(position.z > 20);
assert.equal(grenades.canDamage(Vector3.Zero(), new Vector3(0, 0, 3.9)), true);
assert.equal(grenades.canDamage(Vector3.Zero(), new Vector3(0, 0, 4.1)), false);
const wall = MeshBuilder.CreateBox('wall', {width: 10, height: 10, depth: .2}, scene);
wall.position.z = 2; wall.checkCollisions = true; wall.computeWorldMatrix(true);
assert.equal(grenades.canDamage(Vector3.Zero(), new Vector3(0, 0, 3)), false, 'cover blocks blast');
grenades.throw(Vector3.Zero(), new Vector3(0, 0, 1));
grenades.update(2); assert.ok(position.z < 2, 'swept collision prevents tunnelling');
grenades.throw(Vector3.Zero(), Vector3.Up()); grenades.clear(); grenades.update(3);
assert.equal(explosions, 2, 'round reset cancels pending grenade');
assert.equal(applyWeaponDamage(100, 'grenade', 'body'), 66);
assert.equal(applyWeaponDamage(100, 'grenade', 'head'), 66);
grenades.dispose(); scene.dispose(); engine.dispose();
console.log('PASS: two-second airborne fuse, one explosion, 4m radius, cover, collision, reset and 34 damage.');
