import assert from 'node:assert/strict';
import { registerHooks } from 'node:module';
registerHooks({ resolve(s, c, next) {
  if (s.startsWith('.') && !/\.[a-z]+$/i.test(s)) return next(s + '.ts', c);
  return next(s, c);
}});
const { localWeaponTesting } = await import('../game/localWeaponTesting.ts');
const { createOrbWallet, WALLET_STORAGE_KEY } = await import('../game/createOrbWallet.ts');
assert.equal(localWeaponTesting(true, 'localhost'), true);
assert.equal(localWeaponTesting(true, '127.0.0.1'), true);
assert.equal(localWeaponTesting(false, 'localhost'), false);
assert.equal(localWeaponTesting(true, 'thecooldude2486-cell.github.io'), false);
const values = new Map([[WALLET_STORAGE_KEY, JSON.stringify({ orbs: 37, sniperOwned: true, orbClicks: 4 })]]);
const storage = { getItem: k => values.get(k), setItem: (k, v) => values.set(k, v) };
const original = values.get(WALLET_STORAGE_KEY);
const preview = createOrbWallet(storage, true);
for (const key of ['uziOwned', 'molotovOwned', 'rocketOwned', 'sniperOwned']) assert.equal(preview.state[key], true);
for (const buy of ['buyUzi', 'buyMolotov', 'buyRocket', 'buySniper']) assert.equal(preview[buy](), 'owned');
assert.equal(preview.state.orbs, 37);
assert.equal(values.get(WALLET_STORAGE_KEY), original);
preview.award(5);
const live = createOrbWallet(storage);
assert.equal(live.state.orbs, 42);
assert.equal(live.state.uziOwned, false);
assert.equal(live.state.molotovOwned, false);
assert.equal(live.state.rocketOwned, false);
assert.equal(live.state.sniperOwned, true, 'real existing unlock is preserved');
assert.equal(live.state.orbClicks, 4);
assert.equal(live.buyUzi(), 'insufficient');
console.log('PASS: local-only weapon access, no charges, no saved free unlocks, production lock and preserved progress.');
