import assert from 'node:assert/strict';
import { registerHooks } from 'node:module';
registerHooks({ resolve(s, c, next) {
  if (s.startsWith('@babylonjs/core/') && !s.endsWith('.js')) return next(s + '.js', c);
  if (s.startsWith('.') && !/\.[a-z]+$/i.test(s)) return next(s + '.ts', c);
  return next(s, c);
}});
const { createOrbWallet, WALLET_STORAGE_KEY, MOLOTOV_PRICE } = await import('../game/createOrbWallet.ts');
const { createMolotovs, MOLOTOV } = await import('../game/createMolotov.ts');
const { applyWeaponDamage } = await import('../game/weaponDefinitions.ts');
const { NullEngine, Scene, MeshBuilder, Vector3 } = await import('@babylonjs/core');
const values = new Map([[WALLET_STORAGE_KEY, JSON.stringify({ orbs: 249, sniperOwned: true, rocketOwned: true, orbClicks: 20 })]]);
const storage = { getItem: key => values.get(key), setItem: (key, value) => values.set(key, value) };
const wallet = createOrbWallet(storage);
assert.equal(MOLOTOV_PRICE, 250);
assert.equal(wallet.state.molotovOwned, false);
assert.equal(wallet.buyMolotov(), 'insufficient');
wallet.award(1); assert.equal(wallet.buyMolotov(), 'purchased');
assert.equal(wallet.state.orbs, 0); assert.equal(wallet.buyMolotov(), 'owned');
assert.equal(createOrbWallet(storage).state.molotovOwned, true);
assert.equal(wallet.state.sniperOwned, true); assert.equal(wallet.state.rocketOwned, true);
assert.equal(wallet.state.orbiterOwned, true);
const failed = createOrbWallet({ getItem: () => JSON.stringify({ orbs: 250 }), setItem() { throw Error(); } });
assert.equal(failed.buyMolotov(), 'unavailable'); assert.equal(failed.state.orbs, 250);
assert.equal(applyWeaponDamage(100, 'molotov', 'body'), 95);
assert.equal(applyWeaponDamage(100, 'molotov', 'head'), 95);
const engine = new NullEngine(), scene = new Scene(engine);
const floor = MeshBuilder.CreateBox('floor', { width: 40, depth: 40, height: .2 }, scene);
floor.position.y = -.1; floor.checkCollisions = true; floor.computeWorldMatrix(true);
let ticks = 0, last;
const fire = createMolotovs(scene, p => { ticks++; last = p; });
fire.throw(new Vector3(0, 1, 0), Vector3.Down());
for (let i = 0; i < 100 && !scene.getTransformNodeByName('Ember burning area'); i++) fire.update(.01);
assert.ok(scene.getTransformNodeByName('Ember burning area'), 'landing creates area');
assert.equal(ticks, 0, 'no impact damage or instant burn');
fire.update(.49); assert.equal(ticks, 0);
fire.update(.01); assert.equal(ticks, 1);
assert.ok(fire.canDamage(last, new Vector3(2, 1, 0)));
assert.equal(fire.canDamage(last, new Vector3(4, 1, 0)), false);
assert.equal(fire.canDamage(last, new Vector3(0, 4, 0)), false, 'cannot burn through upper floor');
const wall = MeshBuilder.CreateBox('wall', { width: .2, height: 3, depth: 8 }, scene);
wall.position.set(1, 1.5, 0); wall.checkCollisions = true; wall.computeWorldMatrix(true);
assert.equal(fire.canDamage(last, new Vector3(2, 1, 0)), false, 'wall blocks fire');
wall.dispose();
fire.update(4.5); assert.equal(ticks, 10, 'exactly 50 damage over five seconds');
assert.equal(scene.getTransformNodeByName('Ember burning area'), null);
fire.update(10); assert.equal(ticks, 10);
fire.throw(new Vector3(0, 1, 0), Vector3.Down()); fire.update(.1);
fire.clear(); fire.update(10); assert.equal(ticks, 10, 'round reset clears flight and burn');
assert.equal(scene.getTransformNodeByName('thrown Molotov'), null);
fire.dispose(); scene.dispose(); engine.dispose();
console.log('PASS: Molotov price, ownership, save failures, damage, landing, ticks, duration, radius, cover and cleanup.');
