import assert from 'node:assert/strict';
import { registerHooks } from 'node:module';
registerHooks({ resolve(s, c, next) {
  if (s.startsWith('@babylonjs/core/') && !s.endsWith('.js')) return next(s + '.js', c);
  if (s.startsWith('.') && !/\.[a-z]+$/i.test(s)) return next(s + '.ts', c);
  return next(s, c);
}});
import { smoothPose, MOVEMENT_SEND_MS } from '../game/onlineMovement.ts';
assert.equal(MOVEMENT_SEND_MS, 50);
const start = { x: 0, y: .9, z: -17, yaw: Math.PI - .05, pitch: 0 };
const target = { x: 5, y: 2, z: -10, yaw: -Math.PI + .05, pitch: .5 };
const oneFrame = smoothPose(start, target, 1 / 60);
assert.ok(oneFrame.x > 0 && oneFrame.x < target.x, 'interpolates rather than teleports');
assert.ok(Math.abs(oneFrame.yaw - start.yaw) < .1, 'takes shortest turn across pi');
let current = start;
for (let i = 0; i < 120; i++) current = smoothPose(current, target, 1 / 60);
assert.ok(Math.abs(current.x - target.x) < .001);
assert.ok(Math.abs(current.y - target.y) < .001);
assert.ok(Math.abs(current.pitch - target.pitch) < .001);
assert.deepEqual(smoothPose(start, target, 0), start);
console.log('PASS: fixed 20Hz send rate, smooth position/pitch and shortest-path facing interpolation.');
const { NullEngine, Scene } = await import('@babylonjs/core');
const { createRemotePlayer } = await import('../game/createRemotePlayer.ts');
const engine = new NullEngine(), scene = new Scene(engine);
const remote = createRemotePlayer(scene);
remote.show(start);
const root = scene.getTransformNodeByName('online remote player');
assert.equal(root.isEnabled(), true); assert.equal(root.position.z, -17);
remote.receive(target); remote.update(1 / 60);
assert.ok(root.position.x > 0 && root.position.x < 5);
for (let i = 0; i < 120; i++) remote.update(1 / 60);
assert.ok(Math.abs(root.position.x - 5) < .001);
assert.ok(Math.abs(scene.getMeshByName('online head').rotation.x - .5) < .001);
assert.ok(root.getChildMeshes().every(mesh => !mesh.isPickable && !mesh.checkCollisions));
remote.hide(); assert.equal(root.isEnabled(), false);
remote.show({ ...start, z: 17 }); assert.equal(root.position.z, 17, 'new session resets smoothing');
remote.dispose(); assert.equal(scene.getTransformNodeByName('online remote player'), null);
scene.dispose(); engine.dispose();
console.log('PASS: actual remote model position, facing, pitch, noncombat meshes, hide/rejoin and cleanup.');
