import assert from 'node:assert/strict';
import { registerHooks } from 'node:module';
registerHooks({resolve(s,c,next) { return next(s.startsWith('.') && !/\.[a-z]+$/i.test(s) ? s + '.ts' : s,c); }});
const { NullEngine, Scene, MeshBuilder, Vector3 } = await import('@babylonjs/core');
const { createRockets, ROCKET } = await import('../game/createRockets.ts');
assert.equal(ROCKET.speed, 45);
const { getWeaponDamage, applyWeaponDamage } = await import('../game/weaponDefinitions.ts');
const { createOrbWallet, WALLET_STORAGE_KEY } = await import('../game/createOrbWallet.ts');
const data = new Map([[WALLET_STORAGE_KEY, JSON.stringify({orbs: 299, sniperOwned: true, orbClicks: 20})]]);
const storage = {getItem: k => data.get(k) ?? null, setItem: (k,v) => data.set(k,v)};
let wallet = createOrbWallet(storage);
assert.equal(wallet.buyRocket(), 'insufficient'); wallet.award(1);
assert.equal(wallet.buyRocket(), 'purchased'); assert.equal(wallet.state.orbs, 0);
assert.equal(wallet.buyRocket(), 'owned'); wallet = createOrbWallet(storage);
assert.equal(wallet.state.rocketOwned, true); assert.equal(wallet.state.sniperOwned, true); assert.equal(wallet.state.orbiterOwned, true);
const blocked = createOrbWallet({getItem: () => JSON.stringify({orbs: 300}), setItem() {throw Error('blocked');}});
assert.equal(blocked.buyRocket(), 'unavailable'); assert.equal(blocked.state.orbs, 300); assert.equal(blocked.state.rocketOwned, false);
assert.equal(getWeaponDamage('rocketLauncher', 'direct'), 67);
assert.equal(getWeaponDamage('rocketLauncher', 'splash'), 34);
assert.equal(applyWeaponDamage(100, 'rocketLauncher', 'direct'), 33);
assert.equal(applyWeaponDamage(100, 'rocketLauncher', 'splash'), 66);
assert.equal(getWeaponDamage('rocketLauncher', 'head'), 34, 'splash has no head multiplier');
const engine = new NullEngine(), scene = new Scene(engine);
const target = MeshBuilder.CreateBox('bot target', {size: 1}, scene); target.position.z = 5; target.metadata = {owner: 'bot'}; target.computeWorldMatrix(true);
let explosions = 0, direct, health = 100;
const rockets = createRockets(scene, (p, mesh) => { explosions++; direct = mesh; health = applyWeaponDamage(health, 'rocketLauncher', mesh === target ? 'direct' : 'splash'); });
rockets.fire(Vector3.Zero(), new Vector3(0,0,1)); rockets.update(.05); assert.equal(explosions, 0);
rockets.update(.2); assert.equal(direct, target); assert.equal(health, 33); rockets.update(1); assert.equal(explosions, 1, 'no double damage');
const wall = MeshBuilder.CreateBox('wall', {width: 8, height: 8, depth: .1}, scene); wall.position.z = 2; wall.checkCollisions = true; wall.computeWorldMatrix(true);
rockets.fire(Vector3.Zero(), new Vector3(0,0,1)); rockets.update(.5); assert.equal(direct, wall, 'nearest wall intercepts rocket');
rockets.fire(Vector3.Zero(), new Vector3(0,0,1)); rockets.clear(); rockets.update(1); assert.equal(explosions, 2);
rockets.dispose(); scene.dispose(); engine.dispose();
console.log('PASS: price, save, legacy unlocks, direct 67 / splash 34, single damage, faster flight, walls and cleanup.');
